namespace Entities.Concrete.Enums
{
    /// <summary>Denetim günlüğü olay türü (sabit kod; mesaj/şikayet metni tutulmaz).</summary>
    public enum AuditAction
    {
        AccountClosed = 1,
        ChatMessageSentAppointmentThread = 2,
        ChatMessageSentFavoriteThread = 3,
        ChatMediaMessageSent = 4,
        ChatMessageHiddenForUser = 5,
        ChatThreadHiddenForUser = 6,

        AuthOtpVerificationFailed = 7,
        AuthLoginSuccess = 8,
        AuthRegisterSuccess = 9,
        AuthRefreshSuccess = 10,
        AuthLogout = 11,

        AppointmentCreated = 12,
        AppointmentStoreLinkedToExisting = 13,
        AppointmentApprovedByStore = 14,
        AppointmentRejectedByStore = 15,
        AppointmentApprovedByFreeBarber = 16,
        AppointmentRejectedByFreeBarber = 17,
        AppointmentApprovedByCustomer = 18,
        AppointmentRejectedByCustomer = 19,
        AppointmentCancelled = 20,
        AppointmentCompleted = 21,
        AppointmentHiddenByUser = 22,
        AppointmentHiddenByUserBulk = 23,

        BarberStoreDeleted = 24,
        FreeBarberPanelDeleted = 25,
        ComplaintCreated = 26,
        RatingDeleted = 27,
        ManuelBarberDeleted = 28,
        RatingCreated = 29,
        FavoriteAdded = 30,
        FavoriteRemoved = 31,
        UserBlocked = 32,
        UserUnblocked = 33,
        RequestCreated = 34,
        RequestDeleted = 35,
        SavedFilterCreated = 36,
        SavedFilterUpdated = 37,
        SavedFilterDeleted = 38,
        BarberStoreCreated = 39,
        BarberStoreUpdated = 40,
        FreeBarberPanelCreated = 41,
        FreeBarberPanelUpdated = 42,
        ManuelBarberCreated = 43,
        ComplaintDeleted = 44,
        ManuelBarberUpdated = 45,

        // --- Admin panel aksiyonları ---
        // actorUserId = aksiyonu yapan admin id (AdminUser.Id), resourceId = hedef User/AdminUser id
        AdminUserBanned = 100,
        AdminUserUnbanned = 101,
        AdminSubscriptionUpdated = 102,
        AdminCreated = 103,
        AdminDeleted = 104,
        AdminActivated = 105,
        AdminDeactivated = 106,
        AdminChatThreadViewed = 107,
        AdminAuditLogViewed = 108,
        AdminProfileUpdated = 109,
        AdminPasswordChanged = 110,
        AdminCategoryCreated = 111,
        AdminCategoryUpdated = 112,
        AdminCategoryDeleted = 113,
        AdminHelpGuideCreated = 114,
        AdminHelpGuideUpdated = 115,
        AdminHelpGuideDeleted = 116,
        AdminHelpGuideActiveChanged = 117,
        AdminComplaintResolved = 118,
        AdminRequestProcessed = 119,
        AdminAppointmentCancelled = 120,
        AdminBarberStoreSuspended = 121,
        AdminBarberStoreUnsuspended = 122,
        AdminFreeBarberSuspended = 123,
        AdminFreeBarberUnsuspended = 124,
        AdminRatingDeleted = 125,
        AdminAiChatCompleted = 126,
        AdminBroadcastSent = 127,
        AdminMediaDeleted = 128,
        AdminSocialPostRemoved = 129,
        AdminSocialStoryRemoved = 130,
        AdminSocialProfileRemoved = 131,
        AdminSocialHighlightRemoved = 132,
        AdminSocialProfileRestored = 133,
        AdminRatingHidden = 134,
        AdminRatingUnhidden = 135,
        AdminSocialCommentRemoved = 136,
    }
}
