-- PostgreSQL: HelpGuides tablosunu güncel uygulama metinleriyle doldurur.
-- Çalıştırmadan önce yedek alın. UserType: 0=Müşteri, 1=Serbest Berber, 2=Berber Dükkanı

DELETE FROM "HelpGuides";

-- ========== MÜŞTERİ (0) ==========
INSERT INTO "HelpGuides" ("Id","UserType","Title","Description","TranslationKey","Order","IsActive","CreatedAt","UpdatedAt") VALUES
(gen_random_uuid(), 0, 'Genel bakış', 'Panelden yakınınızdaki berber dükkanları ve serbest berberleri keşfedersiniz. Randevular, Mesajlar, Favoriler ve Profil sekmeleri tüm hesap türlerinde ortaktır; üstte bildirim zili anlık uyarıları açar.', 'hg_c_01', 1, true, NOW(), NOW()),
(gen_random_uuid(), 0, 'Konum ve keşif', 'Yakın listeler için konum izni gerekir. Harita veya liste üzerinden işletme veya serbest berber kartına giderek detay, çalışma saatleri, hizmetler ve randevu alma akışına ulaşırsınız.', 'hg_c_02', 2, true, NOW(), NOW()),
(gen_random_uuid(), 0, 'İki taraflı randevu (siz + tek taraf)', 'Doğrudan bir berber dükkanı veya yayında olan bir serbest berber ile randevu oluşturduğunuzda süreç iki taraflıdır: siz ve işletme ya da siz ve serbest berber. Onay/red, iptal ve tamamlama bu iki taraf üzerinden ilerler.', 'hg_c_03', 3, true, NOW(), NOW()),
(gen_random_uuid(), 0, 'Üç taraflı randevu (müşteri + serbest berber + dükkan)', 'Serbest berber müşteriyle anlaşıp bir dükkan koltuğunda kesim yapacaksa süreç üç taraflıdır. Müşteri talebini oluşturur; serbest berber uygun dükkan ve koltuğu seçer; dükkan tarafı isteği değerlendirir. Her aşamada bildirim gider; süre aşımında sistem ilgili tarafı bilgilendirir (ör. dükkan seçimi veya son onay zaman aşımı).', 'hg_c_04', 4, true, NOW(), NOW()),
(gen_random_uuid(), 0, 'Dükkan seçimi: İsteğime göre / Dükkan seç', 'Serbest berber ile randevuda işletme seçim tipi randevunun gidişatını belirler. İsteğime göre: başlangıçta sadece siz ve serbest berber; dükkan sonra devreye girebilir. Dükkan seç: serbest berber randevu notuyla birlikte belirli bir dükkan ve koltuk üzerinden ilerler.', 'hg_c_05', 5, true, NOW(), NOW()),
(gen_random_uuid(), 0, 'Randevu durumları', 'Beklemede: tarafların onayı bekleniyor. Onaylandı: kesinleşti. Reddedildi / İptal: ilgili taraf süreci sonlandırdı. Yanıtlanmadı: süre içinde cevap verilmedi. Tamamlandı: hizmet bitti; değerlendirme yapılabilir.', 'hg_c_06', 6, true, NOW(), NOW()),
(gen_random_uuid(), 0, 'Bildirimler ve randevu eylemleri', 'Üstteki çan simgesi bildirim listesini açar. Randevu oluşturma, onay, red, iptal, hatırlatma ve üç taraflı akıştaki ara adımlar (ör. dükkanın seçimi onayı, serbest berberin ilk reti, son müşteri onayı) push ve uygulama içi bildirimlerle size iletilir. Aynı olaylar Randevular ekranındaki kart üzerinden de yönetilir.', 'hg_c_07', 7, true, NOW(), NOW()),
(gen_random_uuid(), 0, 'Favoriler ve mesaj ilişkisi', 'Bir işletmeyi veya serbest berberi favoriye eklediğinizde, Mesajlar sekmesinde ilgili sohbet hattı açılır. Mesajlaşmak için karşı tarafın favorilerinizde aktif olması gerekir; favoriyi kaldırırsanız bağlantı kopar ve yeni mesaj gönderemezsiniz.', 'hg_c_08', 8, true, NOW(), NOW()),
(gen_random_uuid(), 0, 'Mesajlar sekmesi', 'Aktif favori thread''lerinizi listeler. Sohbetten randevu kartlarına veya profillere gidebilir, yanıt ve medya paylaşımı yapabilirsiniz. Engelleme durumunda mesajlaşma engellenir.', 'hg_c_09', 9, true, NOW(), NOW()),
(gen_random_uuid(), 0, 'Randevu oluştururken koltuk ve hizmet', 'Dükkan randevularında uygun koltuk ve müsait saat seçilir. İşletme yüzdelik (komisyon) modelinde en az bir hizmet seçmek zorunludur; saatlik kira modelinde hizmet seçimi zorunlu olmayabilir. Toplam süre çalışma saatleri ve çakışma kurallarına tabidir.', 'hg_c_10', 10, true, NOW(), NOW()),
(gen_random_uuid(), 0, 'Değerlendirme ve tamamlama', 'Randevu tamamlandıktan sonra ilgili tarafı yıldız ve yorumla değerlendirebilirsiniz. Tamamlanmayan veya iptal edilen randevularda akış buna göre kapanır.', 'hg_c_11', 11, true, NOW(), NOW()),
(gen_random_uuid(), 0, 'Müşteri numarası', 'Aynı telefonla açılan müşteri, serbest berber ve dükkan hesapları ortak bir müşteri numarası paylaşabilir; destek ve eşleştirme süreçlerinde referans olarak kullanılır.', 'hg_c_12', 12, true, NOW(), NOW()),
(gen_random_uuid(), 0, 'Şikayet, istek ve engellenenler', 'Profilden şikayet ve istek oluşturabilir, engellediğiniz kullanıcıları yönetebilirsiniz. Engel varsa randevu ve mesaj oluşturma kuralları buna göre kısıtlanır.', 'hg_c_13', 13, true, NOW(), NOW()),
(gen_random_uuid(), 0, 'Sesli asistan (mikrofon)', 'Menüden sesli randevu asistanına erişilir; mikrofon izni istenebilir. Asistan randevu oluşturma sürecinde size yardımcı olur; kesin işlemler yine ekran akışına bağlıdır.', 'hg_c_14', 14, true, NOW(), NOW());

-- ========== SERBEST BERBER (1) ==========
INSERT INTO "HelpGuides" ("Id","UserType","Title","Description","TranslationKey","Order","IsActive","CreatedAt","UpdatedAt") VALUES
(gen_random_uuid(), 1, 'Panel ve yayında olma', 'Panelde konumunuz, müsaitlik durumunuz ve profil bilgileriniz yönetilir. Müşterilerin sizi görebilmesi için yayında ve uygun olduğunuzdan emin olun; arka plan konum izni verdiyseniz sistem mesafe kurallarına göre güncelleme yapabilir.', 'hg_fb_01', 1, true, NOW(), NOW()),
(gen_random_uuid(), 1, 'Müşteri ile doğrudan iki taraflı randevu', 'Müşteri sizinle doğrudan randevu aldığında süreç siz ve müşteri arasındadır: onay, red, iptal ve tamamlama bildirimleri bu çerçevede işler.', 'hg_fb_02', 2, true, NOW(), NOW()),
(gen_random_uuid(), 1, 'Üç taraflı randevu (müşteri + siz + dükkan)', 'Müşteri talebini başlattığında uygun dükkan ve koltuğu seçersiniz; dükkanın onayı ve gerekli müşteri onayları tamamlanınca randevu kesinleşir. Serbest berberin ilk aşamada reddi veya dükkanın seçimi reddi bildirimleri ayrı türlerle iletilir; süre aşımlarında sistem bilgilendirme yapar.', 'hg_fb_03', 3, true, NOW(), NOW()),
(gen_random_uuid(), 1, 'Dükkan seçim tipi (müşteri randevusunda)', 'İsteğime göre: başlangıçta dükkan yoktur, süreç ihtiyaca göre şekillenir. Dükkan seç: belirli işletme ve not ile üçlü akış başlatırsınız. Mesafe ve müsaitlik kuralları uygulanır.', 'hg_fb_04', 4, true, NOW(), NOW()),
(gen_random_uuid(), 1, 'Dükkanla kendi randevunuz (siz → işletme)', 'Bir işletmede koltuk ayırarak müşterisiz de randevu oluşturabilirsiniz; bu talep dükkanın onayına gider, hizmet seçimi işletmenin fiyatlandırma tipine göre zorunlu olabilir veya olmayabilir.', 'hg_fb_05', 5, true, NOW(), NOW()),
(gen_random_uuid(), 1, 'Randevu durumları ve zaman aşımı', 'Beklemede ve onay süreleri dolarsa randevu yanıtlanmamış veya ilgili bildirim türleriyle (ör. seçim zaman aşımı) güncellenir. Her durum Randevular ekranında ve bildirimlerde görünür.', 'hg_fb_06', 6, true, NOW(), NOW()),
(gen_random_uuid(), 1, 'Bildirimler', 'Oluşturma, onay, red, iptal, üçlü akış ara adımları, hatırlatmalar ve tamamlanma hatırlatmaları push ile gelir. Üst çan listesinden geçmişe erişirsiniz.', 'hg_fb_07', 7, true, NOW(), NOW()),
(gen_random_uuid(), 1, 'Favoriler ve mesajlar', 'Sizi favorileyen müşteri ile mesajlaşmak için favori ilişkisinin aktif olması gerekir. Mesajlar sekmesi yalnızca bu bağlantı üzerinden iletişimi gösterir.', 'hg_fb_08', 8, true, NOW(), NOW()),
(gen_random_uuid(), 1, 'Kazanç ve fiyatlandırma (dükkanla çalışma)', 'Tamamlanan randevularda işletme yüzdelik modelinde kazancınız, seçilen hizmetlerin toplamından işletmenin belirlediği yüzde kesintisi düşülerek hesaplanır. Saatlik kira modelinde toplam hizmet tutarından, randevu süresi (saat) × saatlik kira bedeli çıkarılır; sonuç sıfırdan küçük olmaz. Müşteri ile doğrudan işlemlerde (dükkan yok) hizmet toplamı size kalır.', 'hg_fb_09', 9, true, NOW(), NOW()),
(gen_random_uuid(), 1, 'Abonelik ve panel erişimi', 'Serbest berber hesabında abonelik/deneme durumunuz profil ve abonelik ekranından takip edilir; süresi dolmuş veya engellenmiş hesaplarda kullanım kısıtları uygulanır.', 'hg_fb_10', 10, true, NOW(), NOW()),
(gen_random_uuid(), 1, 'Konum izinleri', 'Ön plan konumu yakın listeler için kullanılır. Arka plan izni verirseniz uygulama kapalıyken de belirlenen mesafe ve süre kurallarıyla konum güncellenebilir; bildirim çubuğunda servis bilgisi gösterilebilir.', 'hg_fb_11', 11, true, NOW(), NOW()),
(gen_random_uuid(), 1, 'Profil ve görünürlük', 'Fotoğraf, iletişim ve hizmet bilgilerinizi güncel tutun; müşteri güveni ve randevu dönüşümü için önemlidir.', 'hg_fb_12', 12, true, NOW(), NOW()),
(gen_random_uuid(), 1, 'Sesli asistan', 'Menüden mikrofon ile randevu asistanını açabilirsiniz; asistan yönlendirme yapar, kesin işlemler ekran akışıyla tamamlanır.', 'hg_fb_13', 13, true, NOW(), NOW()),
(gen_random_uuid(), 1, 'Şikayet ve engel', 'Profilden şikayet veya istek oluşturabilir, engellediğiniz kullanıcılarla randevu ve mesajın kısıtlandığını unutmayın.', 'hg_fb_14', 14, true, NOW(), NOW());

-- ========== BERBER DÜKKANI (2) ==========
INSERT INTO "HelpGuides" ("Id","UserType","Title","Description","TranslationKey","Order","IsActive","CreatedAt","UpdatedAt") VALUES
(gen_random_uuid(), 2, 'İşletme paneli', 'Dükkan bilgileri, çalışma saatleri, koltuklar, manuel berberler, hizmet ve fiyatlar panelden yönetilir. Müşteri ve serbest berber randevuları Randevular sekmesinde birleşik görünür.', 'hg_st_01', 1, true, NOW(), NOW()),
(gen_random_uuid(), 2, 'Koltuklar ve manuel berber', 'Her koltuk için ayrı müsaitlik ve randevu kısıtları vardır. Manuel berber kayıtları hizmet sunumunu organize etmenize yardımcı olur; çakışma kontrolleri otomatik uygulanır.', 'hg_st_02', 2, true, NOW(), NOW()),
(gen_random_uuid(), 2, 'Fiyatlandırma: Yüzdelik (komisyon)', 'Yüzdelik modelde işletme, tamamlanan randevudaki hizmet toplamından kendi belirlediği yüzdeyi (PricingValue) kesinti olarak alır. Bu modelde randevu oluştururken en az bir hizmet seçilmesi zorunludur.', 'hg_st_03', 3, true, NOW(), NOW()),
(gen_random_uuid(), 2, 'Fiyatlandırma: Saatlik kira', 'Kira modelinde işletme, randevunun süresi (bitiş − başlangıç saati) ile saatlik kira bedelini (PricingValue) çarpar; bu tutar hizmet toplamından düşülür. Hizmet satırı seçimi zorunlu olmayabilir. Kesinti negatif olmaz.', 'hg_st_04', 4, true, NOW(), NOW()),
(gen_random_uuid(), 2, 'Müşteri randevuları (iki taraflı)', 'Müşteri doğrudan dükkanınıza randevu aldığında onay/red, iptal ve tamamlama sizin ve müşteri arasında yürür; bildirimler her iki tarafa gider.', 'hg_st_05', 5, true, NOW(), NOW()),
(gen_random_uuid(), 2, 'Serbest berber randevuları', 'Serbest berber kendi adına sizden koltuk ayırttığında talep size düşer; onay veya red ile süreci yönetirsiniz. Üçlü akışta müşteri de devreye girdiğinde ara onaylar ve zaman aşımı bildirimleri oluşur.', 'hg_st_06', 6, true, NOW(), NOW()),
(gen_random_uuid(), 2, 'Üç taraflı süreçte dükkanın rolü', 'Serbest berber dükkan ve koltuk seçtikten sonra siz seçimi değerlendirirsiniz. Ret veya onay bildirimleri müşteri ve serbest berbere iletilir. Son müşteri onayı veya redleri ve süre aşımları sistem tarafından ayrı bildirim türleriyle yönetilir.', 'hg_st_07', 7, true, NOW(), NOW()),
(gen_random_uuid(), 2, 'Randevu durumları', 'Beklemede, onaylandı, reddedildi, iptal, yanıtlanmadı ve tamamlandı durumları listelerde ve kartlarda gösterilir; işletme tarafı uygun aksiyonları (onay/red/iptal) kullanabilir.', 'hg_st_08', 8, true, NOW(), NOW()),
(gen_random_uuid(), 2, 'Bildirimler', 'Randevu oluşturulması, onaylar, redler, üçlü akış adımları, hatırlatmalar ve tamamlanma uyarıları çan menüsünde toplanır.', 'hg_st_09', 9, true, NOW(), NOW()),
(gen_random_uuid(), 2, 'Mesajlar ve favoriler', 'Sizi favorileyen kullanıcılarla mesajlaşma için favori bağlantısının aktif olması gerekir. Engellenen kullanıcılarla mesaj ve randevu kısıtları uygulanır.', 'hg_st_10', 10, true, NOW(), NOW()),
(gen_random_uuid(), 2, 'Kazanç özeti', 'Raporlama ekranlarında tamamlanan randevular üzerinden, tanımlı yüzdelik veya saatlik kira kurallarınıza göre işletme payınız hesaplanır; serbest berber kazancı ayrı hesaplanır.', 'hg_st_11', 11, true, NOW(), NOW()),
(gen_random_uuid(), 2, 'Abonelik', 'Dükkan hesabında abonelik/deneme durumu profil ve abonelik bölümünden izlenir; süresi dolunca kullanım kısıtları devreye girer.', 'hg_st_12', 12, true, NOW(), NOW()),
(gen_random_uuid(), 2, 'Profil ve görünürlük', 'Adres, fotoğraflar, çalışma saatleri ve fiyatların güncel olması müşteri güveni ve randevu kalitesi için kritiktir.', 'hg_st_13', 13, true, NOW(), NOW()),
(gen_random_uuid(), 2, 'Şikayet ve istek', 'Operasyonel sorunları profil üzerinden şikayet veya istek kaydı ile iletebilirsiniz.', 'hg_st_14', 14, true, NOW(), NOW());
